[control_plane]
100.48.5.49 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[workers]
3.236.177.241 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519
3.236.41.201 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519

[all:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
